<?php
/**
 * Show earned points for product
 * 
 * @see Magestore_Customerreward_Block_Product_Spend
 */
?>

<?php if ($this->isShowRedeemRules()): ?>
    <?php $_catalogRules = $this->getSpendingRules() ?>
    <?php if (count($_catalogRules)): ?>
    <?php $_formData = $this->getRewardFormData() ?>
    <div class="divider"></div>
    <div class="customerreward-product-rule">
        <div class="list-rule">
            <span><?php echo $this->__('Use Your Points') ?>:</span>
            <select id="reward_product_rule" name="reward_product_rule" class="input-select" onchange="changeRewardProductRule(this);">
                <option value=""><?php echo $this->__('-- Please Select Rule --') ?></option>
                <?php foreach ($_catalogRules as $_rule): ?>
                <option value="<?php echo $_rule->getId() ?>"<?php if ($_formData->getRewardProductRule() == $_rule->getId()): ?> selected="selected"<?php endif ?>>
                    <?php echo $this->escapeHtml($_rule->getName()) ?>
                    (<?php echo $this->__('With %d', $this->getMinRulePoint($_rule)) ?>
                    <?php echo ($_rule->getPointsSpended() == 1) ? $this->__('Point') : $this->__('Points') ?>)
                </option>
                <?php endforeach; ?>
            </select>
            <input type="hidden" id="reward_product_point" name="reward_product_point" value="" />
        </div>
        <div id="customerreward-login-msg" style="display: none;">
            <?php echo $this->__('You need') ?>
            <a href="<?php echo $this->getUrl('customer/account/login') ?>"><?php echo $this->__('login') ?></a>
            <?php echo $this->__('to redeem your point(s) on this product') ?>
        </div>
        <div id="customerreward-needmore-msg" style="display: none;">
            <?php echo $this->__('You need to earn more') ?>
            <span id="customerreward-needmore-points">100</span>
            <?php echo $this->__('point(s) to use this rule.') ?>
            <?php echo $this->__('Please click') ?>
            <a href="<?php echo Mage::helper('customerreward')->getInfoLink() ?>"><?php echo $this->__('here') ?></a>
            <?php echo $this->__('to learn about it.') ?>
        </div>
        <div id="customerreward-slider-container" style="display: none;">
            <div id="customerreward-slider">
                <div id="customerreward-slider-zoom-out"><img src="<?php echo $this->getSkinUrl('images/slider_btn_zoom_out.gif') ?>" alt="<?php echo $this->__('Zoom Out') ?>" title="<?php echo $this->__('Zoom Out') ?>" /></div>
                <div id="customerreward-track">
                    <div id="customerreward-handle"></div>
                </div>
                <div id="customerreward-slider-zoom-in"><img src="<?php echo $this->getSkinUrl('images/slider_btn_zoom_in.gif') ?>" alt="<?php echo $this->__('Zoom In') ?>" title="<?php echo $this->__('Zoom In') ?>" /></div>
            </div>
            <div class="customerreward-slider-label">
                <span><span id="customerreward-slider-label">100</span> <?php echo $this->__('Points') ?></span>
            </div>
        </div>
        <div id="customerreward-price-template" style="display: none;">
            <span class="price">
                <span class="price"></span>
                <?php echo $this->__('with') ?>
                <span class="points"></span>
                <?php echo $this->__('Point(s)') ?>
            </span>
        </div>
    </div>
    <script type="text/javascript">
        var rewardProductRules = <?php echo $this->getProductRulesJson($_catalogRules) ?>;
        var currentRuleOptions = {};
        var needChangeRewardManual = true;
        function changeRewardProductRule(el) {
            var ruleId = el.value;
            rewardPrice.clearPrices();
            if (ruleId) {
                currentRuleOptions = rewardProductRules[ruleId];
                switch (currentRuleOptions.optionType) {
                    case 'login':
                        showRewardInfo('customerreward-login-msg');
                        break;
                    case 'needPoint':
                        showRewardInfo('customerreward-needmore-msg');
                        $('customerreward-needmore-points').innerHTML = currentRuleOptions.needPoint;
                        break;
                    case 'slider':
                        showRewardInfo('customerreward-slider-container');
                        rewardSlider.applyOptions(currentRuleOptions.sliderOption);
                        break;
                    case 'static':
                        $('reward_product_point').value = currentRuleOptions.sliderOption.minPoints;
                        rewardPrice.showPointPrices(currentRuleOptions.sliderOption.pointStep, currentRuleOptions);
                        needChangeRewardManual = false;
                        showRewardInfo('');
                        break;
                }
            } else {
                showRewardInfo('');
            }
        }
        function changePointCallback(points) {
            rewardPrice.showPointPrices(points, currentRuleOptions);
        }
        function showRewardInfo(elId) {
            var elIds = ['customerreward-login-msg', 'customerreward-needmore-msg', 'customerreward-slider-container'];
            for (var i = 0; i < 3; i++){
                if (elIds[i] == elId) {
                    $(elId).show();
                } else {
                    $(elIds[i]).hide();
                }
            }
        }
        var rewardSlider;
        var rewardPrice;
        //Event.observe(window, 'load', function(){
            $('customerreward-slider-container').show();
            rewardSlider = new PointSlider(
                'reward_product_point',
                'customerreward-track',
                'customerreward-handle',
                'customerreward-slider-zoom-out',
                'customerreward-slider-zoom-in',
                'customerreward-slider-label'
            );
            rewardSlider.changePointCallback = changePointCallback;
            $('customerreward-slider-container').hide();
            
            var pricesElements = $$('.product-shop .price-box .regular-price, .product-shop .price-excluding-tax .price, .product-shop .price-including-tax .price, .product-shop .price-as-configured .full-product-price');
            var specials = $$('.product-shop .special-price .price');
            if (typeof specials[0] != 'undefined') {
                pricesElements.push(specials[0]);
            }
            rewardPrice = new RewardPrice(
                'customerreward-price-template',
                pricesElements,
                <?php echo $this->getProduct()->getFinalPrice() ?>,
                <?php echo $this->getPriceFormatJs() ?>
            );
            
            changeRewardProductRule($('reward_product_rule'));
            if (needChangeRewardManual) {
                rewardSlider.manualChange(<?php echo $_formData->getRewardProductPoint() ?>);
            }
        //});
    </script>
    <?php endif; ?>
<?php endif; ?>
