<?php
	/**
	 * Description for offer template
	 */
?>
<div class="entry-edit-head">
    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Description') ?></h4>
</div>
<div id="offer_description_fieldset" class="fieldset">
	<div class="hor-scroll">
		<p><?php echo $this->__('Offer is displayed on "Share With Friend" page of each product and "Checkout Success" page. When sharing an offer link/coupon with friends, customers can earn point(s). If the invited-friends click or buy products via this link or they use the coupon code to buy products, refferals will receive a corresponding number of point(s).') ?></p>
	</div>
</div>