<script type="text/javascript">
//<![CDATA[
function changeDiagramsPeriod(periodObj) {
	periodParam = periodObj.value ? 'period/' + periodObj.value + '/' : '';
<?php foreach ($this->getChild('diagrams')->getTabsIds() as $tabId): ?>
	ajaxBlockParam = 'block/adminhtml_report_right_<?php echo $tabId ?>/';
	ajaxBlockUrl = '<?php echo $this->getUrl('*/*/ajaxBlock', array('_current' => true, 'block' => '', 'period' => '')) ?>' + ajaxBlockParam + periodParam;
	new Ajax.Request(ajaxBlockUrl, {
		parameters: {isAjax: 'true', form_key: FORM_KEY},
		onSuccess: function(transport) {
			tabContentElementId = '<?php echo $this->getChild('diagrams')->getId() ?>_<?php echo $tabId ?>_content';
			try {
				if (transport.responseText.isJSON()) {
					var response = transport.responseText.evalJSON()
					if (response.error) {
						alert(response.message);
					}
					if(response.ajaxExpired && response.ajaxRedirect) {
						setLocation(response.ajaxRedirect);
					}
				} else {
					$(tabContentElementId).update(transport.responseText);
				}
			}
			catch (e) {
				$(tabContentElementId).update(transport.responseText);
			}
		}
	});
<?php endforeach; ?>
	ajaxBlockUrl = '<?php echo $this->getUrl('*/*/ajaxBlock', array('_current' => true, 'block' => 'diagrams_totals', 'period' => '')) ?>' + periodParam;
	new Ajax.Request(ajaxBlockUrl, {
		parameters: {isAjax: 'true', form_key: FORM_KEY},
		onSuccess: function(transport) {
			tabContentElementId = 'dashboard_diagram_totals';
			try {
				if (transport.responseText.isJSON()) {
					var response = transport.responseText.evalJSON()
					if (response.error) {
						alert(response.message);
					}
					if(response.ajaxExpired && response.ajaxRedirect) {
						setLocation(response.ajaxRedirect);
					}
				} else {
					$(tabContentElementId).replace(transport.responseText);
				}
			}
			catch (e) {
				$(tabContentElementId).replace(transport.responseText);
			}
		}
	});
}
//]]>
</script>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3 class="head-dashboard customerreward-statistic-head"><?php echo $this->__('Reward System Report') ?></h3></td>
        </tr>
    </table>
</div>

<div class="dashboard-container customerreward-statistic-container">
    <?php echo $this->getChildHtml('store_switcher') ?>
    <table cellspacing="25" width="100%">
        <tr>
            <td style="width: 30%">
                <div class="entry-edit" class="a-center bold">
            		<div class="entry-edit-head">
                        <h4><?php echo $this->__('Spend/Earn Ratio') ?></h4>
                    </div>
            		<fieldset id="commissions_diagram_content" class="np">
            			<?php echo $this->getChildHtml('earn_to_spend') ?>
            		</fieldset>
            	</div>
            	
                <?php echo $this->getChildHtml('cost_of_loyatlymember') ?>
                <div class="entry-edit" class="a-center bold">
            		<div class="entry-edit-head">
                        <h4><?php echo $this->__('Earning Distribution') ?></h4>
                    </div>
            		<fieldset id="commissions_diagram_content" class="np">
            			<?php echo $this->getChildHtml('earning_distribution') ?>
            		</fieldset>
            	</div>
                <?php echo $this->getChildHtml('average_value_per_point') ?>
            </td>
            <td>
                <div class="entry-edit" style="border:1px solid #ccc;">
                    <?php echo $this->getChildHtml('diagrams') ?>
                    <?php if (is_array($this->getChild('diagrams')->getTabsIds())) : ?>
                        <div id="diagram_tab_content"></div>
                    <?php endif; ?>
                </div>
            </td>
        </tr>
    </table>
</div>

<script type="text/javascript">
//<![CDATA[
    $('order_newloyaltymember_period').value ='7d';
    $('order_earnedspent_period').value ='7d';
    $('order_averageorderpointearned_period').value ='7d';
    $('order_storesignups_period').value ='7d';
    $('order_newslettersubscription_period').value ='7d';
    $('order_productreview_period').value ='7d';
    //]]>
</script>