<?php if (1): ?>
<div class="entry-edit">
	<div class="entry-edit-head"><h4><?php echo $this->getHeadTitle() ?></h4></div>
	<fieldset class="a-center bold">
		<div class="customerreward-statistic-content">
            <?php echo $this->getContent(); ?>
		</div>
        <div class="customerreward-statistic-comment" style="font-weight:normal">
            <?php echo $this->getExplanation(); ?>
        </div>
	</fieldset>
</div>
<?php endif ?>
