<?php
$currency = Mage::getModel('directory/currency')->load(Mage::app()->getStore()->getBaseCurrencyCode());
?>
<div id="messages">
    <ul class="messages">
        <li class="notice-msg">
            <ul>
                <li><span><?php echo $this->__('Example:') ?></span>
                </li>
            </ul>
            <?php echo $this->__('1. Example 1:'); ?>
            <div style="margin-left: 50px">
                <?php echo $this->__('- Choose “Discount Type”: "By fixed amount" or "To fixed amount"') ?>
                </br>
                <?php echo $this->__('- Fill in field "Discount Amount": 10') ?>
                </br>
                <?php echo $this->__('- Fill in field "Uses Allowed Per Product": 5') ?>
                </br>
                <?php echo $this->__('=> You can discount by or to each X points (configured in tab Conditions) %s and apply to maximum 5 times per product.', $currency->format(10)) ?>
            </div>
            <?php echo $this->__('2. Example 2:'); ?>
            <div style="margin-left: 50px">
                <?php echo $this->__('- Choose "Discount Type": "By Percentage of the original price" or "To Percentage of the original price"') ?>
                </br>
                <?php echo $this->__('- Fill in field: "Discount Amount": 10') ?>
                </br>
                <?php echo $this->__('- Fill in field: "Uses Allowed Per Product": 5') ?>
                </br>
                <?php echo $this->__('=> You can discount by or to each X points (configured in tab Conditions) %s of the original price and apply to maximum 5 times per product.', $currency->format(10)) ?>
            </div>
        </li>
    </ul>
</div>