<?php
	/**
	 * Transaction history template
	 */
?>
<?php $collection = $this->getCollection() ?>
<?php if ($collection->getSize()): ?>
<div class="box-account box-info box-customerreward-history">
	<div class="box-head">
		<h2><?php echo $this->__('Transactions history') ?></h2>
	</div>
	<?php echo $this->getPagerHtml() ?>
	<div class="">
	<table class="data-table" id="transactions-history-new">
		<col class="id" />
		<col class="points" />
		<col class="title" />
		<col class="date" />
		<col class="expired" />
		<thead>
			<tr>
				<th><?php echo $this->__('ID') ?></th>
				<th><?php echo $this->__('Point(s)') ?></th>
				<th><?php echo $this->__('Title') ?></th>
				<th><?php echo $this->__('Date') ?></th>
				<th><?php echo $this->__('Expired') ?></th>
			</tr>
			<tbody>
				<?php foreach($collection as $item): ?>
				<tr>
					<td><?php echo $item->getId() ?></td>
					<td><?php echo $item->getPointsChange() ?></td>
					<td><?php echo $item->getActionInstance()->getTitleHtml(false) ?></td>
					<td>
						<?php echo $this->formatDate($item->getCreateAt(),'short',true) ?>
						<?php if ($item->getData('expiration_date')): ?>
							<div class="expiration-date">
								<?php echo $this->__('Expires on ') ?>
								<?php echo $this->formatDate($item->getData('expiration_date')) ?>
							</div>
						<?php endif ?>
					</td>
					<td><?php echo $item->getIsExpired() ? $this->__('Yes') : $this->__('No') ?></td>
				</tr>
				<?php endforeach ?>
			</tbody>
		</thead>
	</table>
	<script type="text/javascript">decorateTable('transactions-history-new');</script>
	</div>
	<?php echo $this->getPagerHtml() ?>
	<div class="box-bottom">		
	</div>
</div>
<?php endif ?>